version: 2
jobs:
    build:
        docker:
            - image: bocinsky/bocin_base:latest
        steps:
            - checkout
            - setup_remote_docker:   # (2)
                docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
            - run:
                name: Install Docker client
                command: |
                    set -x
                    VER="18.03.0-ce"
            - run: docker info